### ISSUE TITLE
What's a "visual command?"

### ISSUE THREAD

**Issue by trev-dev** [iostapyshyn/eshell-vterm#4]
This may seem silly, but I actually don't have any appreciation for what a visual command is. I found this package and hope that it will, perhaps, clear up some of the poor handling of visual feedback that eshell has.

What is `eshell-vterm` for dummies?

**Comment by fenix011** [comment]
I'm curious... too, what do you guys understand as a 'visual-command' ? 

Ah, oh...wait, are you referring to things like 'htop' ,.. aren't you ?

Anyways, thanks, thanks, thanks

**Comment by iostapyshyn** [comment]
@fenix011 That is correct. Note, however, that the term is not my invention. Eshell already calls these commands visual (`C-h v eshell-visual-commands RET`), but uses `term-mode` to execute them, which is objectively inferior to `vterm`

**Comment by iostapyshyn** [comment]
To answer @trev-dev’s question directly, `eshell-vterm` executes commands specified in `eshell-visual-{commands,options,subcommands}` in a `vterm` buffer.

**Comment by fenix011** [comment]
ah. uh... yet, i tried M-x 'eshell-vterm' with no luck. What am i missing here ?
Thanks, thanks, thanks

**Comment by iostapyshyn** [comment]
It's a global minor mode. After enabling it via `M-x eshell-vterm-mode`, visual commands issued in `eshell` will be executed in a `vterm` buffer.
