### ISSUE TITLE
Vterm buffer does NOT inherit eshell buffer `process-environment` 

### ISSUE THREAD

**Issue by danilevy1212** [iostapyshyn/eshell-vterm#5]
This is the same as not inheriting the environment variables of the `eshell` buffer. This makes a very poor integration with tools like  `direnv`. 

To prove this, I create a small script

```sh
#!/usr/bin/env sh

printenv > environment.txt
```

Set a env variable for testing a exec the script from eshell:

```sh
$ [eshell] setenv TEST_VAR test_val
$ [eshell] sh script.sh
```

Then you can find TEST_VAR in environment.txt. But running:

```sh
$ [eshell] eshell-vterm-visual-exec ./script.sh
```

The variable is not there.

It's a bit strange, this seems like a problem with visual commands In general, since it also happens with the unadvised version of eshell-visual-exec. I found a work around however,  to set up `vterm-environment` right before.

```sh
$ [eshell] setq vterm-environment $process-environment
$ [eshell] eshell-vterm-visual-exec ./script.sh 
```

And you will find it there.

**Comment by danilevy1212** [comment]
For know, I am using this a as workaround in my init.el

```lisp
(add-hook 'eshell-pre-command-hook
          (lambda ()
            (setq dan/vterm-environment-old vterm-environment
                  vterm-environment process-environment)))
(add-hook 'eshell-post-command-hook
          (lambda ()
            (setq vterm-environment dan/vterm-environment-old)))
```

**Comment by danilevy1212** [comment]
I simplified my solution, using [inheritenv](https://github.com/purcell/inheritenv) package in melpa:

```
(eval-after-load 'eshell-vterm
    '(inheritenv-add-advice #'eshell-vterm-exec-visual))
```

**Comment by iostapyshyn** [comment]
I can't seem to reproduce this now. Can you confirm the bug still exists?

**Comment by danilevy1212** [comment]
Sorry, don't actively use emacs anymore. I believe this bug came from my nixos installation anyway, forgot to close this ticket when I discovered that. Closing.
