### ISSUE TITLE
How can I make visual buffer quit after process is finished

### ISSUE THREAD

**Issue by Inc0n** [iostapyshyn/eshell-vterm#7]
As title, the visual commands once finished, its process is alway done, but the buffer doesn't close immediately, I can kill the buffer manually. 

So I wonder if there is a way to automate this.

**Comment by gaoDean** [comment]
set `eshell-destroy-buffer-when-process-dies` to `t`. That will kill the buffer if the process exits with 0

**Comment by Inc0n** [comment]
Perfect :)
